asn2139\_hw2
================
Akanksha Nalatwad

``` r
library(tidyverse)
```

    ## ── Attaching packages ──────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ─────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

Importing Dataset

``` r
trash_df=
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet="Mr. Trash Wheel",
  range=cell_cols("A:N")) %>% 
      janitor::clean_names () %>% 
     drop_na(dumpster) %>% 
    mutate(
      sports_balls= round(sports_balls),
      sports_balls= as.integer(sports_balls)
    )
```

Read preciptation data for 2017 and 2018

``` r
precip_2018=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet="2018 Precipitation",
             skip=1) %>% 
            janitor::clean_names () %>% 
            drop_na(month) %>% 
            mutate(year=2018) %>% 
            relocate(year)

precip_2017=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet="2017 Precipitation",
             skip=1
             ) %>% 
            janitor::clean_names() %>% 
            drop_na(month) %>% 
            mutate(year=2017) %>% 
            relocate(year)
```

``` r
month_df=
      tibble(
            month=1:12,
            month_name=month.name
      )
        
precip_df=bind_rows(precip_2018, precip_2017)

precip_dif= left_join(precip_df, month_df, by="month")
```

This dataset contains information from the Mr. Trashwheel trash
collector in Baltimore, Maryland. As trash enters the inner harbor, the
trashwheel collects that trash, and stores it in a dumpster. The dataset
contains information on year, month, and trash collected, include some
specific kinds of trash. There are a total of 344 rows in our final
dataset. Additional data sheets include month precipitation data. In
this dataset:

  - The median number of sports balls found in a dumpster in 2017 was 8
  - The total precipitation in 2018 was 70.33 inches.

## Problem 2

``` r
transit_df=
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select (line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada) %>% 
  mutate(entry=ifelse(entry=="YES",TRUE,FALSE)) %>% 
  mutate(vending=ifelse(vending=="YES", TRUE, FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

## Description of Dataset

There are 19 characteristics describing the 1868 entrys and exits of
subway stations in NYC. The lines includeed in this dataset are 4
Avenue, 42nd St Shuttle, 6 Avenue, 63rd Street, 8 Avenue, Archer Av,
Astoria, Brighton, Broadway, Broadway Jamaica, Broadway-7th Ave,
Canarsie, Clark, Concourse, Coney Island, Crosstown, Culver, Dyre Av,
Eastern Parkway, Flushing, Franklin, Fulton, Jerome, Lenox, Lexington,
Liberty, Myrtle, Nassau, New Lots, Nostrand, Pelham, Queens Boulevard,
Rockaway, Sea Beach, West End, White Plains Road.The routes in this data
set include R, N, F, B, GS, A, C, E, Q, D, J, L, 1, G, 2, 5, FS, 3, 7,
4, 6, M, e, H. The types of entrances described are Stair, Elevator,
Easement, Escalator, Door, Ramp, Walkway.

Answer the following questions using these data:

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St A/B/C/D; 125st 1; 125st 4/5);
the distinct function may be useful here.

``` r
distinct(transit_df,station_name,line)
```

    ## # A tibble: 465 x 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # … with 455 more rows

There are 465 station names in this dataset.

How many stations are ADA compliant?

``` r
var(transit_df)
```

    ## Warning in var(transit_df): NAs introduced by coercion

    ##                   line station_name station_latitude station_longitude route1
    ## line                NA           NA               NA                NA     NA
    ## station_name        NA           NA               NA                NA     NA
    ## station_latitude    NA           NA     0.0049528259      0.0006516714     NA
    ## station_longitude   NA           NA     0.0006516714      0.0032753303     NA
    ## route1              NA           NA               NA                NA     NA
    ## route2              NA           NA               NA                NA     NA
    ## route3              NA           NA               NA                NA     NA
    ## route4              NA           NA               NA                NA     NA
    ## route5              NA           NA               NA                NA     NA
    ## route6              NA           NA               NA                NA     NA
    ## route7              NA           NA               NA                NA     NA
    ## route8              NA           NA               NA                NA     NA
    ## route9              NA           NA               NA                NA     NA
    ## route10             NA           NA               NA                NA     NA
    ## route11             NA           NA               NA                NA     NA
    ## entry               NA           NA               NA                NA     NA
    ## vending             NA           NA               NA                NA     NA
    ## entrance_type       NA           NA               NA                NA     NA
    ## ada                 NA           NA               NA                NA     NA
    ##                   route2 route3 route4 route5 route6 route7 route8 route9
    ## line                  NA     NA     NA     NA     NA     NA     NA     NA
    ## station_name          NA     NA     NA     NA     NA     NA     NA     NA
    ## station_latitude      NA     NA     NA     NA     NA     NA     NA     NA
    ## station_longitude     NA     NA     NA     NA     NA     NA     NA     NA
    ## route1                NA     NA     NA     NA     NA     NA     NA     NA
    ## route2                NA     NA     NA     NA     NA     NA     NA     NA
    ## route3                NA     NA     NA     NA     NA     NA     NA     NA
    ## route4                NA     NA     NA     NA     NA     NA     NA     NA
    ## route5                NA     NA     NA     NA     NA     NA     NA     NA
    ## route6                NA     NA     NA     NA     NA     NA     NA     NA
    ## route7                NA     NA     NA     NA     NA     NA     NA     NA
    ## route8                NA     NA     NA     NA     NA     NA     NA     NA
    ## route9                NA     NA     NA     NA     NA     NA     NA     NA
    ## route10               NA     NA     NA     NA     NA     NA     NA     NA
    ## route11               NA     NA     NA     NA     NA     NA     NA     NA
    ## entry                 NA     NA     NA     NA     NA     NA     NA     NA
    ## vending               NA     NA     NA     NA     NA     NA     NA     NA
    ## entrance_type         NA     NA     NA     NA     NA     NA     NA     NA
    ## ada                   NA     NA     NA     NA     NA     NA     NA     NA
    ##                   route10 route11 entry vending entrance_type ada
    ## line                   NA      NA    NA      NA            NA  NA
    ## station_name           NA      NA    NA      NA            NA  NA
    ## station_latitude       NA      NA    NA      NA            NA  NA
    ## station_longitude      NA      NA    NA      NA            NA  NA
    ## route1                 NA      NA    NA      NA            NA  NA
    ## route2                 NA      NA    NA      NA            NA  NA
    ## route3                 NA      NA    NA      NA            NA  NA
    ## route4                 NA      NA    NA      NA            NA  NA
    ## route5                 NA      NA    NA      NA            NA  NA
    ## route6                 NA      NA    NA      NA            NA  NA
    ## route7                 NA      NA    NA      NA            NA  NA
    ## route8                 NA      NA    NA      NA            NA  NA
    ## route9                 NA      NA    NA      NA            NA  NA
    ## route10                NA      NA    NA      NA            NA  NA
    ## route11                NA      NA    NA      NA            NA  NA
    ## entry                  NA      NA    NA      NA            NA  NA
    ## vending                NA      NA    NA      NA            NA  NA
    ## entrance_type          NA      NA    NA      NA            NA  NA
    ## ada                    NA      NA    NA      NA            NA  NA

``` r
ada_compliant=
select(transit_df, ada)

  summary(ada_compliant)
```

    ##     ada         
    ##  Mode :logical  
    ##  FALSE:1400     
    ##  TRUE :468

468 stations are ADA compliant.

What proportion of station entrances / exits without vending allow
entrance?

``` r
no_vending_df=
filter(transit_df,vending=="NO")


no_vending_entry_df=
filter(no_vending_df,entry=="TRUE" )

(nrow(no_vending_entry_df))/(nrow(no_vending_df))
```

    ## [1] NaN

The proportion is NaN.

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?

\#\#Problem 3

Loading, cleaning, and making changes to pols\_df

``` r
pols_df=
  read_csv("./data/pols-month.csv") %>% 
   janitor::clean_names() %>% 
   separate("mon", c("year", "month", "day"), sep="-") %>% 
    mutate(month =recode(month,'01'="jan",'02'="feb", '03'="mar", '04'="apr",'05'="may",
                               '06'="jun",'07'="jul",'08'="aug",'09'="sept", '10'="oct",
                               '11'="nov",'12'="dec")) %>% 
    mutate(prez_gop = recode(prez_gop, "1"="gop","0"="dem")) %>% 
    rename(president=prez_gop) %>% 
    select(-prez_dem,-day) 
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

    ## Warning: Problem with `mutate()` input `prez_gop`.
    ## ℹ Unreplaced values treated as NA as .x is not compatible. Please specify replacements exhaustively or supply .default
    ## ℹ Input `prez_gop` is `recode(prez_gop, `1` = "gop", `0` = "dem")`.

    ## Warning: Unreplaced values treated as NA as .x is not compatible. Please specify
    ## replacements exhaustively or supply .default

``` r
snp_df=
  read_csv("./data/snp.csv") %>% 
  janitor::clean_names() %>% 
   separate("date", c("month", "day", "year"), sep="/") %>% 
    mutate(month =recode(month,'01'="jan",'02'="feb", '03'="mar", '04'="apr",'05'="may",
                               '06'="jun",'07'="jul",'08'="aug",'09'="sept", '10'="oct",
                               '11'="nov",'12'="dec")) %>% 
    relocate(year,month) %>% 
    select(-day) 
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

import and tidy umemployment dataset

``` r
unemploy_df=
  read_csv("./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(jan:feb:mar:apr:may:jun:jul:aug:sep:oct:nov:dec,
               values_to= "unemployed") %>% 
  rename(month=name) %>% 
  mutate(year=as.character(month))
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

    ## Warning in x:y: numerical expression has 2 elements: only the first used

    ## Warning in x:y: numerical expression has 3 elements: only the first used

    ## Warning in x:y: numerical expression has 4 elements: only the first used

    ## Warning in x:y: numerical expression has 5 elements: only the first used

    ## Warning in x:y: numerical expression has 6 elements: only the first used

    ## Warning in x:y: numerical expression has 7 elements: only the first used

    ## Warning in x:y: numerical expression has 8 elements: only the first used

    ## Warning in x:y: numerical expression has 9 elements: only the first used

    ## Warning in x:y: numerical expression has 10 elements: only the first used

    ## Warning in x:y: numerical expression has 11 elements: only the first used

joining the datasets

``` r
compiled_df=
left_join(pols_df,snp_df, by=c("month","year")) 

left_join(compiled_df,snp_df, by=c("month","year")) 
```

    ## # A tibble: 822 x 11
    ##    year  month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close.x
    ##    <chr> <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  jan   dem            23      51     253      23      45     198      NA
    ##  2 1947  feb   dem            23      51     253      23      45     198      NA
    ##  3 1947  mar   dem            23      51     253      23      45     198      NA
    ##  4 1947  apr   dem            23      51     253      23      45     198      NA
    ##  5 1947  may   dem            23      51     253      23      45     198      NA
    ##  6 1947  jun   dem            23      51     253      23      45     198      NA
    ##  7 1947  jul   dem            23      51     253      23      45     198      NA
    ##  8 1947  aug   dem            23      51     253      23      45     198      NA
    ##  9 1947  sept  dem            23      51     253      23      45     198      NA
    ## 10 1947  oct   dem            23      51     253      23      45     198      NA
    ## # … with 812 more rows, and 1 more variable: close.y <dbl>
